default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  user: postgres
  password: p******

development:
  <<: *default
  database: FlightBooking_development
